# Terminal App
# Universal activity viewer - catches all activities, especially unhandled entities
# "If you see it here, we need to build an app for it"

id: terminal
name: Terminal
icon: icon.svg
description: View all AI activity as terminal output

# Wildcard: subscribe to ALL entities
# Terminal is the fallback for anything that doesn't have a dedicated app
entities:
  - '*'

views:
  # Main view - shows all activities as terminal output
  main:
    title: Terminal
    toolbar:
      - component: layout/stack
        props:
          direction: horizontal
          gap: 8
          padding: "4px 8px"
        children:
          - component: text
            props:
              content: "$ agent activity"
              variant: code
    
    layout:
      - component: terminal-output
        data:
          source: activities
          limit: 50
        item_component: terminal-line
        item_props:
          entity: "{{entity}}"
          operation: "{{operation}}"
          connector: "{{connector}}"
          request: "{{request}}"
          response: "{{response}}"
          status: "{{status}}"
          error: "{{error}}"
          timestamp: "{{created_at}}"
          pending: "{{pending}}"

  # About view
  about:
    title: About Terminal
    layout:
      - component: layout/stack
        props:
          gap: 16
          align: center
          padding: 24
        children:
          - component: text
            props:
              content: Terminal
              variant: title
              align: center
          - component: text
            props:
              content: View all AI activity as terminal output
              variant: body
              align: center
          - component: text
            props:
              content: "If you see an entity here, it means we need to build a dedicated app for it."
              variant: caption
              align: center

default_view: main
