# Settings App
# System preferences and configuration for AgentOS

id: settings
name: Settings
icon: icon.svg
description: Configure AgentOS preferences, themes, and more

# Menu bar configuration
menus:
  - name: Settings
    items:
      - label: About Settings
        action: open_view
        view: about

views:
  # About view - shows AgentOS info
  about:
    title: About AgentOS
    layout:
      - component: layout/stack
        props:
          gap: 20
          align: center
          padding: 32
        children:
          - component: text
            props:
              content: "⚙️"
              variant: title
              align: center
          - component: text
            props:
              content: AgentOS
              variant: title
              align: center
          - component: layout/stack
            props:
              gap: 8
              align: center
            children:
              - component: text
                props:
                  content: "The semantic layer between AI assistants and your digital life"
                  variant: body
                  align: center
              - component: text
                props:
                  content: "Version 0.1.0"
                  variant: caption
                  align: center
              - component: text
                props:
                  content: "Source: apps/settings/app.yaml"
                  variant: caption
                  align: center

  # Themes view - list available themes
  themes:
    title: Themes
    layout:
      - component: layout/scroll-area
        children:
          - component: layout/stack
            props:
              gap: 12
              padding: 16
            children:
              - component: text
                props:
                  content: "Available Themes"
                  variant: title
              - component: text
                props:
                  content: "Themes control the look and feel of your desktop. More themes coming soon."
                  variant: body

default_view: about
