# Group Entity
# A social community or group (Facebook Groups, Reddit subreddits, Discord servers)
#
# Design principle: Groups are communities where people gather around shared interests.
# Distinct from organizations (companies/institutions) - groups are social communities.

id: group
plural: groups
name: Group
description: A social community or group

references:
  schema_org: https://schema.org/Organization  # Closest match
  wikidata: Q16818150  # online community

properties:
  id:
    type: string
    required: true
    description: Unique identifier

  name:
    type: string
    required: true
    description: Group name

  description:
    type: string
    description: Group description/about text

  url:
    type: string
    format: url
    required: true
    description: Group URL

  member_count:
    type: string
    description: Member count as string (e.g., "2.3K", "78,000")
    # Raw format preserves platform-specific notation

  member_count_numeric:
    type: integer
    description: Parsed member count as integer (null if parsing fails)
    # Parsed for sorting/filtering

  privacy:
    type: string
    enum: [OPEN, CLOSED, SECRET]
    description: Privacy setting (OPEN = public, CLOSED = members only, SECRET = hidden)

  created_at:
    type: datetime
    description: When group was created

  updated_at:
    type: datetime
    description: Last activity timestamp

operations: [list, get, search]

display:
  primary: name
  secondary: member_count
  description: description
  icon: users

# Views for rendering group activities
views:
  # List view - shows group.list and group.search results
  list:
    title: "Groups"
    layout:
      - component: list
        data:
          source: activity
        item_component: group-item
        item_props:
          id: "{{id}}"
          name: "{{name}}"
          description: "{{description}}"
          memberCount: "{{member_count}}"
          memberCountNumeric: "{{member_count_numeric}}"
          privacy: "{{privacy}}"
          url: "{{url}}"
        footer:
          count: "{{activity.response.length}}"
          source: "{{activity.plugin}}"
          duration: "{{activity.duration_ms}}"

  search:
    title: "Search Results"
    layout:
      - component: list
        data:
          source: activity
        item_component: group-item
        item_props:
          id: "{{id}}"
          name: "{{name}}"
          description: "{{description}}"
          memberCount: "{{member_count}}"
          memberCountNumeric: "{{member_count_numeric}}"
          privacy: "{{privacy}}"
          url: "{{url}}"
        footer:
          count: "{{activity.response.length}}"
          source: "{{activity.plugin}}"
          duration: "{{activity.duration_ms}}"

  # Single group view
  get:
    title: "{{activity.response.name}}"
    layout:
      - component: layout/scroll-area
        children:
          - component: layout/stack
            props:
              direction: vertical
              gap: "16px"
            children:
              # Group header
              - component: group-header
                props:
                  name: "{{activity.response.name}}"
                  description: "{{activity.response.description}}"
                  memberCount: "{{activity.response.member_count}}"
                  memberCountNumeric: "{{activity.response.member_count_numeric}}"
                  privacy: "{{activity.response.privacy}}"
                  url: "{{activity.response.url}}"
        footer:
          source: "{{activity.plugin}}"
          duration: "{{activity.duration_ms}}"
